#!/bin/sh
while read -r file
do
        case "$1" in
        "w") notify-send "key-handler triggered with: $file" ; setbg "$file" & ;;
        "c")
            [ -z "$destdir" ] && destdir="$(sed "s/#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | awk '{print $2}' | dmenu -l 20 -i -p "Kopiere Datei(en) wohin?" | sed "s|~|$HOME|g")"
		[ ! -d "$destdir" ] && notify-send "$destdir ist kein Verzeichniss, abbruch." && exit
		cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file verschoben nach $destdir." &
		;;
        "m")
		[ -z "$destdir" ] && destdir="$(sed "s/#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | awk '{print $2}' | dmenu -l 20 -i -p "Verschiebe Datei(en) wohin?" | sed "s|~|$HOME|g")"
		[ ! -d "$destdir" ] && notify-send "$destdir ist kein Verzeichniss, abbruch." && exit
		mv "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file verschoben nach $destdir." &
		;;
	"r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"f")
		convert -flop "$file" "$file" ;;
	"y")
		printf "%s" "$file" | tr -d '\n' | xclip -selection clipboard &&
		notify-send "$file in Zwischenablage kopiert" & ;;
	"Y")
		readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
			notify-send "$(readlink -f "$file") in Zwischenablage kopiert" & ;;
	"d")
		[ "$(printf "Nein\\nJa" | dmenu -i -p "$file wirklich löschen?")" = "Ja" ] && rm "$file" && notify-send "$file gelöscht." ;;
	"g")	ifinstalled gimp && setsid -f gimp "$file" ;;
	"i")	notify-send "Information" "$(mediainfo "$file" | sed "s/[ ]\+:/:/g;s/: /: <b>/;s/$/<\/b>/" | grep "<b>")" ;;
        esac
done
